import { type NextPage } from "next";
import Head from "next/head";
import LinkCarousel from "~/components/carousel";
import ImageColumn from "~/components/imageColumn";


const Home: NextPage = (props) => {

  return (
    <>
      <Head>
        <title>Nike Air Max 90 Men&lsquo;s Shoes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/nike-swoosh.ico" />
      </Head>
      <main>
        <LinkCarousel />
        <ImageColumn />
      </main>
    </>
  );
};

export default Home;

